config/routes.rb
Rails.application.routes.draw do
  get "static_pages/home"
  get "/home", to: "static_pages#home"
  get "/help", to: "static_pages#help"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def contact; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "app_name"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand navbar-inverse">
    <div class="container">
      <%= link_to t("app_name"), "#" , class: "navbar-header navbar-brand" %>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item">
            <%= link_to t(".home"), home_path %>
          </li>
          <li class="nav-item">
            <%= link_to t(".help"), help_path %>
          </li>
          <li class="nav-item">
            <%= link_to t(".login"), "#" %>
          </li>
          <% I18n.available_locales.each do |lang| %>
            <li class="nav-item">
              <%= link_to lang.to_s.upcase, (request.path+"?locale=#{lang}") %>
            </li>
            <% end %>
        </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide :title, t(".title") %>
    <div class="jumbotron center">
        <div class="container">
            <h1>
                <%= t ".help_html" %>
            </h1>
            <p>
                <%= t ".para_html" %>
            </p>
        </div>
    </div>

app/views/static_pages/home.html.erb
<div class="jumbotron center">
  <div class="container">
    <h1><%= t ".home_html" %></h1>
    <p><%= t ".para_html" %></p>
    <%= link_to t(".sign_up"), "#", class: "btn btn-primary btn-lg" %>
  </div>
</div>